### ISSUE TITLE
Hiding things when using the grid

### ISSUE THREAD

**Issue by leftieFriele** [nrkno/core-css#38] opened 2017-11-29 14:56 UTC
I have a grid with 4 items, but I want to hide the last two when the viewpart makes the grid trigger _xs_ classes. However there are no classes such as:  nrk-xs-0of12

Is there a reason for this or should I add a PR?

**Comment by eirikbacker** [comment] 2017-11-29 18:35
Hi @leftieFriele :)
The reason is hiding stuff on mobile can be an anti-pattern, so if you need such a util it might be nice to do in you project instead of releasing as a standard? Also - hiding is not related to size, so nrk-xs-hidden might be a more appropriate name? but does it then hide from xs and up (like the size classes)? Bootstrap used to have a system for this (http://getbootstrap.com/docs/3.3/css/#responsive-utilities) but moved away from it in version 4. Let me hear your thoughts :)

**Comment by leftieFriele** [comment] 2017-11-30 09:56
I think it makes sense to add a different layout for lists if the viewport is small. The case in question is a list of four related articles which we want to trim down to just two on small devices. 
I realize why it's not in the grid, and probably shouldn't be there either, but perhaps having utility classes which say something lik _hide when less than_ type thing would be perfect.

**Comment by eirikbacker** [comment] 2018-06-26 14:09
Duplicate of #47

**Closed by eirikbacker** 2018-06-26 14:09 UTC
